[platformio]
default_envs = prod
description = Proyecto D.05 - Despertador FM Real

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
# Filtros recomendados por la normativa para depuración y ver la hora de los logs
monitor_filters = esp32_exception_decoder, time

# Dependencias compartidas para cualquier entorno
lib_deps =
    adafruit/RTClib @ ^2.1.3
    https://github.com/mathertel/Radio.git
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ILI9341 @ ^1.6.0

# ── ENTORN DE PRODUCCIÓ (El que s'executa normalment) ───────────────
[env:prod]
build_flags = 
    -DCORE_DEBUG_LEVEL=3

# ── ENTORN DE TEST (Per avaluar els drivers segons la norma 4.3) ────
[env:test]
test_framework = unity
build_type = debug